#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'Tom Stanton'
__title__ = 'SideroScanner'
__version__ = '0.0.4'
__author_email__ = 'T.D.Stanton@sms.ed.ac.uk'
__description__ = 'A tool for annotating IROMPs in bacteria'
__license__ = 'gpl-3.0'

from argparse import RawTextHelpFormatter, ArgumentParser
from datetime import datetime
from os import cpu_count, remove, uname, path, stat
from shutil import get_terminal_size, rmtree
import pandas as pd
from Bio.SeqIO import to_dict, parse
from pathlib import Path
from tempfile import TemporaryFile
import sideroscanner
from sideroscanner.methods.efetch import efetch
from sideroscanner.methods.build_irompdb import get_fastadb
from sideroscanner.methods.make_db_df import make_db_df
from sideroscanner.methods.seed_blast import seed_blast
from sideroscanner.tools.blast import run_makeblastdb
from sideroscanner.tools.cdhit import run_cdhit
from sideroscanner.tools.hmmer3 import run_hmmbuild
from sideroscanner.tools.muscle import run_muscle
from sideroscanner.tools.trimal import run_trimal

if __name__ == "__main__":
    
    dbpath = f'{path.dirname(sideroscanner.__file__)}/data'
    iromppath = f'{dbpath}/irompdb'
    blastdb = f'{iromppath}/irompdb'
    lib = f'{iromppath}/iromps.hmm'


    parser = ArgumentParser(add_help=False, formatter_class=RawTextHelpFormatter,
                                     usage="sideroscanner-buildhmms",
                                     description='''
SideroScannner: a tool for annotating IROMPs in bacteria
---------------------------------------------------------------''')
    group = parser.add_argument_group("Options")
    group.add_argument('--report', metavar='-', nargs='?', type=str,
                       const=f'seed_alignment_{datetime.today().strftime("%d%m%y_%H%M")}.xlsx',
                       help='''save info about proteins in seed alignment
[optional: path/to/output/file]
[default: seed_alignment_DDMMYY_hhmm.xlsx]
-----------------------------------------------''')
    group.add_argument('-w', metavar='int', type=int, default=2,
                       help='''protein length window [default: 2]
-----------------------------------------------''')
    group.add_argument('-e', metavar='str', type=str, default='1e-200',
                       help='''evalue for blastp [default: 1e-200]
-----------------------------------------------''')
    group.add_argument('-p', metavar='int', type=int, default=100,
                       help='''percent to cluster seeds [default: 100]
-----------------------------------------------''')
    group.add_argument('-t', metavar='int', type=int, default=cpu_count(),
                       help=f'''number of threads [default: {cpu_count()}]
-----------------------------------------------''')
    group.add_argument('--keep', action='store_true',default=False,
                       help='''keep seed alignments
-----------------------------------------------''')
    group.add_argument('--inspect', action='store_true', default=False,
                       help='''print table of reference proteins
-----------------------------------------------''')
    group.add_argument('--append', action='store_true', default=False,
                       help='''add new protein to reference table
-----------------------------------------------''')
    group.add_argument("-h", action="help", help='''show this help message and exit''')
    args = parser.parse_args()


    if not path.isdir(iromppath):
        exit(f'[!] {iromppath} is not an existing directory')

    if not path.isfile(iromppath+'/iromps.csv'):
        exit(f'[!] {iromppath}/iromps.csv not found')

    seed_df = pd.read_csv(iromppath + '/iromps.csv')
    if args.inspect is True:
        exit(seed_df.to_markdown(index=False))

    if args.append is True:
        name = input("[-] Enter protein name (e.g. Fiu): ").strip()
        accession = input("[-] Enter NCBI accession (e.g. WP_004151913.1): ").strip()
        description = input("[-] Enter description (e.g. DHBS receptor): ").strip()
        answer = None
        while answer not in ("y", "n"):
            if name in seed_df["protein"].tolist():
                print(f'[!] {name} exists in reference table:'
                      f'{seed_df[seed_df["protein"] == name].to_string(header=False, index=False)}')
                answer = input(f'[!] Overwrite entry with |{name}|{accession}|{description}| [y/n]: ')
                if answer == "y":
                    seed_df = seed_df[seed_df.protein != name]
                    seed_df = seed_df.append({'protein': name,'acc': accession,
                                    'desc': description}, ignore_index=True)
                    seed_df.to_csv(iromppath + '/iromps.csv', index=False)
                    print(f'[-] Replaced {name}! Now run sideroscanner-buildhmms to add the hmm')
                    exit("[!] Don't forget to overwrite the IROMP HMM library to remove the old entry!")
                elif answer == "n":
                    exit('[!] Exiting')
                else:
                    print("[!] Please enter either [y] or [n]: ")
            else:
                answer = input(f'[!] Append |{name}|{accession}|{description}| to reference table? [y/n]: ')
                if answer == "y":
                    seed_df = seed_df.append({'protein': name,'acc': accession,
                                    'desc': description}, ignore_index=True)
                    seed_df.to_csv(iromppath + '/iromps.csv', index=False)
                    exit(f'[-] Added {name}! Now run sideroscanner-buildhmms to add the hmm')
                elif answer == "n":
                    exit('[!] Exiting')
                else:
                    print("[!] Please enter either [y] or [n]: ")

    append = False
    if path.isfile(lib):
        answer = None
        while answer not in ("append", "overwrite", "exit" ):
            answer = input(f'[!] IROMP HMM library already exists, '
                           f'\033[4ma\033[0mppend, \033[4mo\033[0mverwrite or '
                           f'\033[4me\033[0mxit? [a/o/e]: ')
            if answer == "a":
                append = True
                break
            elif answer == "o":
                break
            elif answer == "e":
                exit('[!] Exiting')
            else:
                print("[!] Please enter either [a], [o] or [e]: ")

    if append is False:
        for i in [".h3i", ".h3p", ".h3f", ".h3m", ""]:
            if path.isfile(f'{lib}{i}'):
                remove(f'{lib}{i}')
    else:
        for i in [".h3i", ".h3p", ".h3f", ".h3m"]:
            if path.isfile(f'{lib}{i}'):
                remove(f'{lib}{i}')

    print(f'[|] \033[4m{__title__} {__version__}\033[0m')
    print(f'[|] Your system is {uname()[0]}')
    if 'Linux' not in uname()[0]:
        print(f'[!] Warning: SideroScanner has not been tested on {uname()[0]}')
    print(f'[|] {datetime.today().strftime("%Y-%m-%d-%H:%M:%S")}')
    if args.t > cpu_count():
        print(f'[!] Number of threads exceeds available CPUs, will use: {cpu_count()}')
        threads = str(cpu_count())
    else:
        threads = str(args.t)
        print(f'[|] Using {threads} threads...')

    print('-' * int(get_terminal_size()[0]))

    proteins = f'{iromppath}/iromps.faa'
    if not path.isfile(blastdb+'.psq') or stat(blastdb+'.psq').st_size < 310000000: # loose size, may need adjusting
        if not path.isfile(proteins) or stat(proteins).st_size < 366000000: # loose size, may need adjusting
            proteins = get_fastadb(iromppath)
        run_makeblastdb(proteins, 'prot', blastdb)

    total_seeds = len(seed_df.index)
    if append is True:
        total_seeds = total_seeds - lib.count('HMMER3/f')

    db_df = make_db_df(proteins)
    db_dict = to_dict(parse(proteins, 'fasta'))
    writer = pd.ExcelWriter(f'{args.report}', engine='xlsxwriter')
    c, d = 0, {}

    alignpath = f'{iromppath}/alignments'
    Path(alignpath).mkdir(parents=True, exist_ok=True)

    for row in seed_df.itertuples():
        if append is True:
            with open(lib) as f:
                if row.acc in f.read():
                    continue
        print('-' * int(get_terminal_size()[0]))
        c += 1
        print(f'[-] Building HMM {c}/{total_seeds} for: {row.protein} ({row.acc})')

        hit_acc = seed_blast(efetch(row.acc), blastdb, args.e, args.w, threads)

        if hit_acc is None:
            print(f'[!] No hits found, review entry')
            continue

        d[row.protein] = str(hit_acc)

        hit_df = pd.DataFrame([sub.split("$") for sub in hit_acc],
                        columns=['accession', 'length', 'id'])

        hit_df = hit_df.merge(db_df, on='accession', how='left')

        hits = ''
        for h in hit_acc:
            hits += db_dict[h.split('$')[0]].format("fasta")
        clustered_hits = run_cdhit(hits, args.p)

        cl_acc = [line.split(' ')[0].replace('>', '') for line in clustered_hits.split('\n') if line.startswith('>')]
        hit_df = hit_df[hit_df['accession'].isin(cl_acc)]
        hit_df.to_excel(writer, sheet_name=row.protein, index=False)

        alignment = run_muscle(clustered_hits, f'{alignpath}/{row.protein}_aligned.faa')
        trimmed = run_trimal(alignment)
        hmm = run_hmmbuild(trimmed, row.protein, f'{iromppath}/{row.protein}.hmm', threads)

        with open(hmm, 'r') as file, open(lib, "a+") as f:
            t1 = file.readlines()
            t1.insert(2, 'ACC   ' + row.acc + '\n')
            t1.insert(3, 'DESC  ' + row.desc + '\n')
            f.writelines(t1)

        print(f'added {row.protein} to HMM library')

        remove(hmm)

    print('-' * int(get_terminal_size()[0]))
    rev_d = {}
    for key, value in d.items():
        try:
            rev_d[value].append(key)
        except:
            rev_d[value] = [key]
    overlap = [value for key, value in rev_d.items() if len(value) > 1]
    if len(overlap) > 0:
        print(f'[!] {", ".join(overlap[0])} share proteins in their seed alignments, review entries')
        print('-' * int(get_terminal_size()[0]))
    print(f'[-] HMMs written to: {iromppath}/iromps.hmm')

    if args.keep is False:
        rmtree(alignpath)
    else:
        print(f'[-] Seed alignments written to: {alignpath}')

    if args.report is not None:
        writer.save()
        print(f'[-] Info written to: {args.report}')
